import asyncio
import json
import subprocess
import sys
import uuid
from datetime import UTC, datetime
from pathlib import Path

from fastapi import APIRouter, Form, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.templating import Jinja2Templates
from sse_starlette.sse import EventSourceResponse

router = APIRouter()
_templates = Jinja2Templates(directory=Path(__file__).parents[1] / "templates")

_TERMINAL = {"completed", "failed"}
_POLL_INTERVAL = 2.5  # seconds


# ── Post-run assembler ────────────────────────────────────────────────────────


def _dur_str(secs: int | None) -> str:
    if secs is None:
        return ""
    return f"{secs // 60}m {secs % 60}s" if secs >= 60 else f"{secs}s"


def _build_post_run(run_id: str) -> dict | None:
    run_dir = Path("runs") / run_id
    if not run_dir.exists():
        return None

    def _r(rel, default=None):
        p = run_dir / rel
        if not p.exists():
            return default
        try:
            return json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            return default

    report = _r("report.json", {})
    phase_summaries = _r("live/phase_summaries.json", [])
    artefacts = _r("live/artefacts.json", {})
    dag_data = _r("live/dag.json", {"nodes": [], "edges": []})
    cg = _r("live/context_graph.json", {"nodes": [], "phases": []})
    brief = _r("input_brief.json", {})
    status_data = _r("live/status.json", {"status": "unknown"})

    dag_by_id = {n["id"]: n for n in dag_data.get("nodes", [])}
    wi_by_id = {n["id"]: n for n in cg.get("nodes", []) if n.get("node_type") == "work_item"}

    def _secs(dag_node: dict) -> int | None:
        s, e = dag_node.get("spawned_at"), dag_node.get("completed_at")
        if not s or not e:
            return None
        try:
            return int((datetime.fromisoformat(e) - datetime.fromisoformat(s)).total_seconds())
        except Exception:
            return None

    phases = []
    for ps in phase_summaries:
        agents = []
        for env in ps.get("envelopes", []):
            aid = env["agent_id"]
            dag_node = dag_by_id.get(aid, {})
            mem = artefacts.get(aid, {}).get("memory", {})
            wi_id = dag_node.get("work_item_id")
            wi = wi_by_id.get(wi_id, {}) if wi_id else {}

            tool_calls = []
            for entry in mem.get("entries", []):
                src = entry.get("source", "unknown")
                val = entry.get("value", {})
                if isinstance(val, dict):
                    query = val.get("query", entry.get("key", ""))
                    snippet = str(val.get("answer", ""))[:300]
                else:
                    query = str(val)[:120]
                    snippet = ""
                tool_calls.append({"source": src, "query": query, "snippet": snippet})

            # Filesystem artefacts (code/docs generated by the agent)
            phase_id = ps.get("phase_id", "")
            art_dir = run_dir / "artefacts" / phase_id / aid
            artefact_files = []
            if art_dir.exists():
                for f in sorted(art_dir.iterdir()):
                    if f.is_file():
                        artefact_files.append(
                            {
                                "filename": f.name,
                                "ext": f.suffix.lstrip(".").lower(),
                            }
                        )

            dur = _secs(dag_node)
            agents.append(
                {
                    "agent_id": aid,
                    "phase_id": phase_id,
                    "role": env.get("role", "").replace("_", " "),
                    "status": env.get("status", "unknown"),
                    "confidence": env.get("confidence"),
                    "verdict": env.get("verdict"),
                    "cost_tokens": env.get("cost_tokens"),
                    "dur_secs": dur,
                    "dur_str": _dur_str(dur),
                    "work_item_name": wi.get("name", ""),
                    "work_item_skills": wi.get("required_skills", []),
                    "tool_calls": tool_calls,
                    "proof": env.get("proof", {}),
                    "artefact_files": artefact_files,
                }
            )

        # Phase wall-clock = earliest spawn → latest completion across its agents
        dag_nodes = [dag_by_id[a["agent_id"]] for a in agents if a["agent_id"] in dag_by_id]
        starts = [n["spawned_at"] for n in dag_nodes if n.get("spawned_at")]
        ends = [n["completed_at"] for n in dag_nodes if n.get("completed_at")]
        phase_dur = None
        if starts and ends:
            try:
                phase_dur = int(
                    (
                        max(datetime.fromisoformat(e) for e in ends)
                        - min(datetime.fromisoformat(s) for s in starts)
                    ).total_seconds()
                )
            except Exception:
                pass

        phases.append(
            {
                "phase_id": ps.get("phase_id"),
                "phase_name": ps.get("phase_name"),
                "synthesis": ps.get("synthesis", ""),
                "mean_confidence": ps.get("mean_confidence"),
                "total_tokens": ps.get("total_tokens", 0),
                "dur_secs": phase_dur,
                "dur_str": _dur_str(phase_dur),
                "agents": agents,
            }
        )

    total_tokens = sum(p.get("total_tokens") or 0 for p in phases)
    all_agents = [a for p in phases for a in p["agents"]]

    doc_path = run_dir / "live" / "final_report.md"
    document = doc_path.read_text(encoding="utf-8") if doc_path.exists() else ""

    return {
        "run_id": run_id,
        "status": status_data.get("status", "unknown"),
        "brief": brief,
        "report": report,
        "document": document,
        "phases": phases,
        "stats": {
            "phase_count": len(phases),
            "agent_count": len(all_agents),
            "total_tokens": total_tokens,
        },
    }


# ── Helpers ───────────────────────────────────────────────────────────────────


def _start_research(project_id: str, run_id: str | None = None) -> str:
    brief_path = Path("output") / project_id / "problem_brief.json"
    if not brief_path.exists():
        raise FileNotFoundError(f"No brief for project {project_id}")

    graph_path = Path("output") / project_id / "context_graph.json"

    if run_id is None:
        run_id = f"{datetime.now(UTC).strftime('%Y%m%d-%H%M%S')}-{uuid.uuid4().hex[:6]}"

    run_dir = Path("runs") / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    (run_dir / "input_brief.json").write_text(
        brief_path.read_text(encoding="utf-8"), encoding="utf-8"
    )
    if graph_path.exists():
        (run_dir / "approved_graph.json").write_text(
            graph_path.read_text(encoding="utf-8"), encoding="utf-8"
        )

    runs_file = Path("output") / project_id / "runs.jsonl"
    existing_ids: set[str] = set()
    if runs_file.exists():
        for line in runs_file.read_text(encoding="utf-8").splitlines():
            try:
                existing_ids.add(json.loads(line)["run_id"])
            except Exception:
                pass
    if run_id not in existing_ids:
        with runs_file.open("a", encoding="utf-8") as f:
            f.write(
                json.dumps(
                    {
                        "run_id": run_id,
                        "started_at": datetime.now(UTC).isoformat(),
                    }
                )
                + "\n"
            )

    subprocess.Popen(
        [sys.executable, "-m", "slow_ai.research", run_id],
        cwd=str(Path.cwd()),
    )
    return run_id


def _read_live(run_id: str, filename: str, default=None):
    path = Path("runs") / run_id / "live" / filename
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def _read_log(run_id: str) -> list[str]:
    path = Path("runs") / run_id / "live" / "log.jsonl"
    if not path.exists():
        return []
    msgs = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            try:
                msgs.append(json.loads(line)["msg"])
            except Exception:
                pass
    return msgs


def _run_state(run_id: str) -> dict:
    status_data = _read_live(run_id, "status.json", {"status": "initializing"})
    dag = _read_live(run_id, "dag.json", {"nodes": [], "edges": []})
    phase_summaries = _read_live(run_id, "phase_summaries.json", [])
    log = _read_log(run_id)
    return {
        "run_id": run_id,
        "status": status_data.get("status", "initializing"),
        "phase_status": status_data.get("phase_status", ""),
        "dag": dag,
        "phase_summaries": phase_summaries,
        "log": log,
    }


# ── Routes ────────────────────────────────────────────────────────────────────


@router.post("/api/runs/launch")
async def launch_run(project_id: str = Form(...)):
    brief_path = Path("output") / project_id / "problem_brief.json"
    if not brief_path.exists():
        return JSONResponse({"error": "Project not found"}, status_code=404)
    try:
        run_id = _start_research(project_id)
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)
    return {"run_id": run_id, "project_id": project_id}


# ── Conversation store (in-memory, keyed by run_id) ──────────────────────────
_conv_sessions: dict[str, list] = {}


def _find_project(run_id: str) -> str | None:
    for runs_file in Path("output").glob("*/runs.jsonl"):
        try:
            for line in runs_file.read_text(encoding="utf-8").splitlines():
                if run_id in line:
                    return runs_file.parent.name
        except Exception:
            pass
    return None


@router.get("/run/{run_id}", response_class=HTMLResponse)
async def run_page(request: Request, run_id: str):
    run_dir = Path("runs") / run_id
    if not run_dir.exists():
        return HTMLResponse("Run not found", status_code=404)

    status_data = _read_live(run_id, "status.json", {"status": "initializing"})
    status = status_data.get("status", "initializing")

    brief_path = run_dir / "input_brief.json"
    brief = {}
    if brief_path.exists():
        try:
            brief = json.loads(brief_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    # For completed runs, assemble results inline so Results tab renders immediately
    post_run = _build_post_run(run_id) if status in _TERMINAL else None

    return _templates.TemplateResponse(
        "views/run.html",
        {
            "request": request,
            "run_id": run_id,
            "brief": brief,
            "status": status,
            "post_run": post_run,
            "start_tab": "results" if status in _TERMINAL else "run",
        },
    )


@router.get("/api/runs/{run_id}/state")
async def run_state_snapshot(run_id: str):
    """Single-shot state snapshot (for completed runs that skip SSE)."""
    run_dir = Path("runs") / run_id
    if not run_dir.exists():
        return JSONResponse({"error": "Run not found"}, status_code=404)
    state = _run_state(run_id)
    state["new_log"] = state["log"]  # alias so client can use same path
    return state


@router.get("/api/runs/{run_id}/post-run")
async def post_run_json(run_id: str):
    data = _build_post_run(run_id)
    if data is None:
        return JSONResponse({"error": "Run not found"}, status_code=404)
    return data


@router.post("/api/runs/{run_id}/chat", response_class=HTMLResponse)
async def run_chat(request: Request, run_id: str, message: str = Form(...)):
    import asyncio

    from slow_ai.agents.run_conversation import run_conversation_turn

    history = _conv_sessions.get(run_id, [])
    try:
        reply, updated = await asyncio.to_thread(run_conversation_turn, message, run_id, history)
        _conv_sessions[run_id] = updated
        # Persist to disk
        from slow_ai.execution.git_store import GitStore

        GitStore(run_id).append_conversation("assistant", reply)
    except Exception as exc:
        reply = f"Sorry, I hit an error: {exc}"

    import html as _html

    escaped = _html.escape(reply, quote=True)
    return HTMLResponse(
        f'<div class="d-flex mb-3">'
        f'<div class="chat-bubble-agent" data-markdown="{escaped}"></div>'
        f"</div>"
    )


@router.post("/api/runs/{run_id}/continue")
async def continue_run(run_id: str):
    """Launch a follow-up run with prior_run_ids pointing at this one."""
    from slow_ai.models import ProblemBrief

    run_dir = Path("runs") / run_id
    if not run_dir.exists():
        return JSONResponse({"error": "Run not found"}, status_code=404)

    brief_path = run_dir / "input_brief.json"
    if not brief_path.exists():
        return JSONResponse({"error": "No brief found"}, status_code=404)

    brief = ProblemBrief.model_validate_json(brief_path.read_text(encoding="utf-8"))
    brief.prior_run_ids = brief.prior_run_ids + [run_id]

    project_id = _find_project(run_id)
    if project_id is None:
        # Create a new project
        import uuid

        project_id = str(uuid.uuid4())
        project_dir = Path("output") / project_id
        project_dir.mkdir(parents=True, exist_ok=True)

    project_dir = Path("output") / project_id
    project_dir.mkdir(parents=True, exist_ok=True)
    (project_dir / "problem_brief.json").write_text(
        brief.model_dump_json(indent=2), encoding="utf-8"
    )

    try:
        new_run_id = _start_research(project_id)
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)

    return {"run_id": new_run_id, "project_id": project_id}


@router.get("/api/runs/{run_id}/agent/{agent_id}")
async def agent_envelope(run_id: str, agent_id: str):
    """Return the evidence envelope for a specific agent."""
    data = _read_live(run_id, "artefacts.json")
    if data is None or agent_id not in data:
        return JSONResponse({"error": "Envelope not found"}, status_code=404)
    return data[agent_id]["envelope"]


@router.get("/api/runs/{run_id}/artefacts/{phase_id}/{agent_id}/{filename}")
async def artefact_file(run_id: str, phase_id: str, agent_id: str, filename: str):
    """Return the raw text content of a single agent artefact file."""
    path = Path("runs") / run_id / "artefacts" / phase_id / agent_id / filename
    if not path.exists():
        return JSONResponse({"error": "Not found"}, status_code=404)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return {"content": data.get("raw", ""), "filename": filename}
    except Exception:
        return JSONResponse({"error": "Could not read file"}, status_code=500)


@router.get("/api/runs/{run_id}/context-graph")
async def run_context_graph(run_id: str):
    """Return the context graph (phases + work items) for the plan overlay."""
    data = _read_live(run_id, "context_graph.json")
    if data is None:
        return JSONResponse({"nodes": [], "edges": []})
    return data


@router.get("/api/runs/{run_id}/export")
async def export_run(run_id: str, request: Request):
    """Export the final research report as a standalone HTML file."""
    import html as _html

    import mistune

    run_dir = Path("runs") / run_id
    if not run_dir.exists():
        return JSONResponse({"error": "Run not found"}, status_code=404)

    doc_path = run_dir / "live" / "final_report.md"
    if not doc_path.exists():
        return JSONResponse({"error": "Final report not yet generated"}, status_code=404)

    document = doc_path.read_text(encoding="utf-8")

    brief_path = run_dir / "problem_brief.json"
    brief = {}
    if brief_path.exists():
        try:
            brief = json.loads(brief_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    rendered_body = mistune.html(document)
    goal = _html.escape(brief.get("goal", run_id))
    domain = _html.escape(brief.get("domain", ""))
    run_date = datetime.now(UTC).strftime("%B %d, %Y")

    html_content = _templates.TemplateResponse(
        "export/run_export.html",
        {
            "request": request,
            "goal": goal,
            "domain": domain,
            "run_id": run_id,
            "run_date": run_date,
            "rendered_body": rendered_body,
        },
    ).body.decode()

    safe_goal = "".join(c if c.isalnum() or c in "-_ " else "" for c in brief.get("goal", run_id))
    filename = f"research-{safe_goal[:50].strip().replace(' ', '-')}.html"

    from fastapi.responses import Response

    return Response(
        content=html_content,
        media_type="text/html",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/api/runs/{run_id}/phase-summary")
async def run_phase_summary(run_id: str, node_type: str = ""):
    """Return the phase synthesis for a DAG phase node, matched by node_type slug."""
    summaries = _read_live(run_id, "phase_summaries.json", [])
    if not summaries:
        return JSONResponse({"error": "not_complete"}, status_code=404)

    # node_type looks like 'phase_reddit_need_discovery'; strip prefix to get slug
    slug = node_type[len("phase_"):] if node_type.startswith("phase_") else node_type

    for s in summaries:
        phase_slug = (s.get("phase_name") or "").lower().replace(" ", "_")
        if phase_slug == slug:
            return s

    return JSONResponse({"error": "not_found"}, status_code=404)


@router.get("/api/runs/{run_id}/interview")
async def run_interview_data(run_id: str):
    """Return the interview conversation and context graph that launched this run."""
    from app.api.interview import _sessions, _graph_for_cytoscape
    from slow_ai.models import ContextGraph

    project_id = _find_project(run_id)
    if not project_id:
        return {"conversation_log": [], "graph_elements": []}

    # Try in-memory sessions first
    session = next((s for s in _sessions.values() if s.get("project_id") == project_id), None)
    if session:
        graph = session.get("draft_graph")
        return {
            "conversation_log": session.get("conversation_log", []),
            "graph_elements": _graph_for_cytoscape(graph) if graph else [],
        }

    # Fall back to disk
    interviews_dir = Path("output") / "interviews"
    if interviews_dir.exists():
        for session_file in interviews_dir.glob("*/session.json"):
            try:
                meta = json.loads(session_file.read_text(encoding="utf-8"))
                if meta.get("project_id") != project_id:
                    continue
                conv_log = []
                log_file = session_file.parent / "conversation_log.json"
                if log_file.exists():
                    conv_log = json.loads(log_file.read_text(encoding="utf-8"))
                elements = []
                graph_file = session_file.parent / "draft_graph.json"
                if graph_file.exists():
                    try:
                        graph = ContextGraph.model_validate_json(graph_file.read_text(encoding="utf-8"))
                        elements = _graph_for_cytoscape(graph)
                    except Exception:
                        pass
                return {"conversation_log": conv_log, "graph_elements": elements}
            except Exception:
                continue

    return {"conversation_log": [], "graph_elements": []}


@router.get("/api/runs/{run_id}/stream")
async def stream_run(run_id: str, request: Request):
    run_dir = Path("runs") / run_id
    if not run_dir.exists():
        return JSONResponse({"error": "Run not found"}, status_code=404)

    async def generator():
        last_log_count = 0
        while True:
            if await request.is_disconnected():
                break

            state = _run_state(run_id)

            # Only send new log lines to avoid resending everything
            all_log = state["log"]
            new_log = all_log[last_log_count:]
            last_log_count = len(all_log)
            state["new_log"] = new_log

            yield {"data": json.dumps(state, default=str)}

            if state["status"] in _TERMINAL:
                # Send one final update then close
                break

            await asyncio.sleep(_POLL_INTERVAL)

    return EventSourceResponse(generator())
